#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Wizard Itaú — SDC (API de Cobrança V2): do par RSA até o primeiro token OAuth sobre mTLS.
# Só o humano pode fazer estes passos (e-mail do banco, token temporário de uso único, 1Password).
# Nada aqui emite boleto: a Cobrança V2 ainda espera o banco (ver 02-SPEC §Itaú).
#
# Uso: scripts/wizard-sdc-itau.sh            (ITAU_WORKDIR muda a pasta dos arquivos de chave)
# Arquivos de chave/certificado ficam FORA do repositório, em ITAU_WORKDIR, com permissão 600.
# Segredos (Client Secret, chave, certificado) vão para o 1Password — nunca para o .env.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ITAU_WORKDIR="${ITAU_WORKDIR:-$HOME/w/salvei/propostas/sdc/itau}"
ENV_FILE="${ITAU_ENV_FILE:-$SCRIPT_DIR/../.env.itau.local}"   # só valores NÃO secretos (agência, conta, Client ID)
ITAU_STS="${ITAU_STS:-https://sts.itau.com.br}"
CSR="$ITAU_WORKDIR/itau-cert.csr"
CERT_KEY="$ITAU_WORKDIR/itau-cert.key"
CERT="$ITAU_WORKDIR/itau-cert.crt"
RESPOSTA="$ITAU_WORKDIR/itau-solicitacao-resposta.txt"
umask 077

TOTAL_STAGES=7

banner "Itaú Cobrança V2 — certificado e credenciais da SDC"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Agência e conta da SDC"
say "Agência e conta que o Itaú vai usar na cobrança (a SDC confirma ao contato do Itaú)."
note "Não são segredo; ficam em $ENV_FILE para os próximos passos."
ask ITAU_AGENCIA "Agência (4 dígitos):"
ask ITAU_CONTA "Conta com dígito (ex.: 12345-6):"
[[ "$ITAU_AGENCIA" =~ ^[0-9]{4}$ ]] || warn "agência fora do formato de 4 dígitos — confira com a SDC"
write_env ITAU_AGENCIA "$ITAU_AGENCIA"
write_env ITAU_CONTA "$ITAU_CONTA"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Par RSA (já gerado) — só conferir"
say "O par RSA 2048 já foi gerado e a chave pública foi enviada ao contato do Itaú."
say "Aqui só conferimos que a privada existe, é válida e corresponde à pública enviada."
if [[ ! -f "$ITAU_WORKDIR/private.pem" || ! -f "$ITAU_WORKDIR/public.pem" ]]; then
  warn "não achei private.pem/public.pem em $ITAU_WORKDIR"
  say "Sem a privada, o e-mail cifrado do banco não abre. Gere um par novo SÓ se o banco ainda não cifrou nada:"
  note "openssl genrsa -out private.pem 2048 && openssl rsa -in private.pem -pubout -out public.pem"
  exit 1
fi
if openssl rsa -in "$ITAU_WORKDIR/private.pem" -check -noout >/dev/null 2>&1 \
   && diff <(openssl rsa -in "$ITAU_WORKDIR/private.pem" -pubout 2>/dev/null) "$ITAU_WORKDIR/public.pem" >/dev/null; then
  say "${GREEN}✓${RESET} private.pem válida e corresponde a public.pem"
else
  warn "private.pem inválida ou NÃO corresponde a public.pem — pare e resolva antes de seguir"
  exit 1
fi
chmod 600 "$ITAU_WORKDIR/private.pem"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Decifrar o e-mail do banco (Client ID + token temporário)"
say "O Itaú manda por e-mail, cifrados com a nossa chave pública, o Client ID e um token temporário."
warn "Ainda NÃO sabemos o formato exato da cifra (arquivo anexo? base64 no corpo? qual padding?)."
say "Por isso este wizard não roda nenhum comando de decifrar: use o comando que o banco indicar,"
say "em outro terminal, com a chave $ITAU_WORKDIR/private.pem. Exemplos COMUNS (confirme com o banco):"
note "  openssl pkeyutl -decrypt -inkey private.pem -in arquivo.bin"
note "  base64 -d texto.b64 | openssl pkeyutl -decrypt -inkey private.pem -pkeyopt rsa_padding_mode:oaep"
say "Se não estiver claro, pergunte ao contato do Itaú antes de tentar às cegas."
pause "Quando tiver o Client ID e o token temporário em mãos, Enter."
ask ITAU_CLIENT_ID "Client ID:"
# A resposta pode ter sido apagada (o estágio 6 oferece) depois de o certificado ser salvo. Aí o token temporário
# já foi consumido: pedir de novo e refazer o POST só renderia uma recusa do banco. EMITIDO = local | 1password | "".
EMITIDO=""
[[ -s "$RESPOSTA" ]] || EMITIDO=$("$SCRIPT_DIR/itau-sts.sh" emitido "$CERT" "$CERT_KEY") || EMITIDO=""
if [[ -s "$RESPOSTA" ]]; then
  note "Já existe resposta da solicitação em $RESPOSTA — o token temporário não é mais necessário."
  ITAU_TOKEN_TEMPORARIO=""
elif [[ "$EMITIDO" == "1password" ]]; then
  say "O certificado já foi emitido: certificado e chave estão no 1Password, mas não em $ITAU_WORKDIR."
  say "O token temporário foi consumido nessa emissão — não peço de novo nem refaço a solicitação."
  say "Traga os dois arquivos de volta e rode o wizard outra vez:"
  note "  op document get \"Itaú SDC - certificado\" --out-file \"$CERT\""
  note "  op document get \"Itaú SDC - chave do certificado\" --out-file \"$CERT_KEY\""
  note "Se esses itens são de uma emissão antiga que não vale mais, só o banco resolve: peça ao contato do Itaú um"
  note "token temporário NOVO e renomeie os itens no 1Password antes de rodar de novo."
  exit 1
elif [[ "$EMITIDO" == "local" ]]; then
  say "${GREEN}✓${RESET} o certificado já foi emitido: $CERT corresponde à chave $CERT_KEY."
  note "A resposta da solicitação não está mais em $RESPOSTA, mas o token temporário foi consumido nessa emissão:"
  note "não peço de novo nem refaço a solicitação. Sigo com o certificado que já existe."
  ITAU_TOKEN_TEMPORARIO=""
else
  ask_secret ITAU_TOKEN_TEMPORARIO "Token temporário (não aparece na tela):"
  [[ -n "$ITAU_TOKEN_TEMPORARIO" ]] || { warn "o token temporário é obrigatório"; exit 1; }
fi
[[ -n "$ITAU_CLIENT_ID" ]] || { warn "Client ID é obrigatório"; exit 1; }
write_env ITAU_CLIENT_ID "$ITAU_CLIENT_ID"
note "O token temporário NÃO é gravado em lugar nenhum — ele só serve para a solicitação a seguir."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Gerar o CSR do certificado"
say "Chave NOVA do certificado (diferente do par RSA do e-mail) e o pedido de certificado (CSR)."
note "Subject: /CN=$ITAU_CLIENT_ID/OU=SDC/L=SAO PAULO/ST=SP/C=BR"
if [[ "$EMITIDO" == "local" ]]; then
  say "Certificado já emitido para $CERT_KEY — mantive a chave (gerar outra inutilizaria o certificado)."
elif [[ -f "$CSR" || -f "$CERT_KEY" ]] && ! confirm "Já existe CSR/chave em $ITAU_WORKDIR. Sobrescrever?"; then
  say "Mantive os arquivos existentes."
else
  openssl req -new -newkey rsa:2048 -nodes -sha512 \
    -keyout "$CERT_KEY" -out "$CSR" \
    -subj "/CN=${ITAU_CLIENT_ID}/OU=SDC/L=SAO PAULO/ST=SP/C=BR" >/dev/null 2>&1
  chmod 600 "$CERT_KEY" "$CSR"
  say "${GREEN}✓${RESET} gerados $CSR e $CERT_KEY"
fi
if [[ "$EMITIDO" == "local" ]]; then :   # o CSR já cumpriu o papel dele; pode nem existir mais
elif openssl req -in "$CSR" -noout -verify >/dev/null 2>&1; then say "${GREEN}✓${RESET} CSR íntegro"; else warn "CSR inválido"; exit 1; fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Solicitar o certificado ao Itaú"
say "POST $ITAU_STS/seguranca/v1/certificado/solicitacao (text/plain, Bearer = token temporário)."
warn "O token temporário costuma ser de USO ÚNICO e a resposta traz o Client Secret UMA vez só."
note "A resposta é gravada em $RESPOSTA (permissão 600) para você copiar o certificado e o secret."
if [[ "$EMITIDO" == "local" ]]; then
  say "${GREEN}✓${RESET} certificado já emitido — NÃO reenvio a solicitação (o token temporário já foi consumido)"
  note "O Client Secret veio uma única vez, naquela resposta. Se você o guardou, está no 1Password"
  note "(item 'Itaú SDC - Client Secret'). Se foi perdido, só o banco resolve: peça ao contato do Itaú um token"
  note "temporário NOVO, tire $CERT do caminho (mv \"$CERT\" \"$CERT.antigo\") e rode o wizard de novo."
elif [[ -s "$RESPOSTA" ]]; then
  say "${GREEN}✓${RESET} resposta já obtida em $RESPOSTA — NÃO reenvio a solicitação (o secret viria só uma vez)"
elif confirm "Enviar a solicitação agora?"; then
  # token por variável de ambiente local ao comando → stdin do curl (nunca em argv); gravação atômica, nunca sobrescreve
  ITAU_TOKEN_TEMPORARIO="$ITAU_TOKEN_TEMPORARIO" "$SCRIPT_DIR/itau-sts.sh" solicitar "$ITAU_STS" "$CSR" "$RESPOSTA" \
    || { warn "o banco recusou; veja $RESPOSTA.recusa-* e fale com o contato do Itaú antes de tentar de novo"; exit 1; }
  ITAU_TOKEN_TEMPORARIO=""
else
  SKIPPED+=("solicitação do certificado (rode o wizard de novo)")
  finish; exit 0
fi
if [[ "$EMITIDO" != "local" ]]; then
  say "Abra $RESPOSTA. O formato da resposta não é interpretado por este wizard:"
  step "copie o bloco BEGIN/END CERTIFICATE para $CERT"
  step "copie o Client Secret (aparece uma única vez)"
  pause "Quando $CERT estiver salvo, Enter."
fi
if [[ ! -f "$CERT" ]] || ! openssl x509 -in "$CERT" -noout >/dev/null 2>&1; then warn "$CERT ausente ou ilegível"; exit 1; fi
chmod 600 "$CERT"
if diff <(openssl x509 -in "$CERT" -noout -pubkey) <(openssl pkey -in "$CERT_KEY" -pubout) >/dev/null; then
  say "${GREEN}✓${RESET} certificado corresponde à chave gerada"
else
  warn "o certificado NÃO corresponde a $CERT_KEY"; exit 1
fi
note "Vence em: $(openssl x509 -in "$CERT" -noout -enddate | cut -d= -f2) — renovar de 30 a 1 dia antes."
ask_secret ITAU_CLIENT_SECRET "Client Secret (não aparece na tela):"
[[ -n "$ITAU_CLIENT_SECRET" ]] || { warn "Client Secret obrigatório"; exit 1; }
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Guardar no 1Password"
say "Client Secret, chave e certificado vão para o 1Password (cofre padrão da sua sessão op)."
if ! command -v op >/dev/null 2>&1 || ! op whoami >/dev/null 2>&1; then
  warn "op CLI ausente ou sem sessão — rode \`eval \$(op signin)\` e repita este estágio, ou guarde à mão."
  SKIPPED+=("1Password: Client Secret, $CERT_KEY e $CERT")
elif [[ "$EMITIDO" == "local" ]] && op item get "Itaú SDC - certificado" >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} os itens 'Itaú SDC - …' já estão no 1Password — não crio duplicata."
elif confirm "Criar os itens 'Itaú SDC - …' no 1Password agora?"; then
  # o secret vai num template temporário (600) em vez de argv; apagado logo depois
  OP_TPL=$(mktemp)
  S="$ITAU_CLIENT_SECRET" C="$ITAU_CLIENT_ID" python3 -c 'import json,os; print(json.dumps({"title":"Itaú SDC - Client Secret","category":"PASSWORD","fields":[{"id":"password","type":"CONCEALED","purpose":"PASSWORD","label":"password","value":os.environ["S"]},{"id":"client_id","type":"STRING","label":"client_id","value":os.environ["C"]}]}))' > "$OP_TPL"
  op item create --template "$OP_TPL" >/dev/null \
    && say "${GREEN}✓${RESET} Itaú SDC - Client Secret" || SKIPPED+=("1Password: Client Secret")
  rm -f "$OP_TPL"
  op document create "$CERT_KEY" --title "Itaú SDC - chave do certificado" >/dev/null \
    && say "${GREEN}✓${RESET} Itaú SDC - chave do certificado" || SKIPPED+=("1Password: chave")
  op document create "$CERT" --title "Itaú SDC - certificado" >/dev/null \
    && say "${GREEN}✓${RESET} Itaú SDC - certificado" || SKIPPED+=("1Password: certificado")
fi
if [[ -f "$RESPOSTA" ]] && confirm "Apagar $RESPOSTA (contém o Client Secret em claro)?"; then
  rm -f "$RESPOSTA"; say "${GREEN}✓${RESET} resposta apagada"
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Testar o token (client_credentials sobre mTLS)"
say "POST $ITAU_STS/api/oauth/token com o certificado e a chave. O token NÃO é impresso."
if confirm "Pedir um token de teste agora?"; then
  CORPO=$(mktemp)
  STATUS=$(ITAU_CLIENT_ID="$ITAU_CLIENT_ID" ITAU_CLIENT_SECRET="$ITAU_CLIENT_SECRET" \
    "$SCRIPT_DIR/itau-sts.sh" token "$ITAU_STS" "$CERT" "$CERT_KEY" "$CORPO") || STATUS="erro"
  if [[ "$STATUS" == "200" ]] && grep -q '"access_token"' "$CORPO"; then
    say "${GREEN}✓${RESET} token emitido (HTTP 200). O motor usa ITAU_CLIENT_ID/SECRET + ITAU_CERT_FILE/ITAU_KEY_FILE."
  else
    warn "HTTP $STATUS sem access_token — confira Client ID/Secret e se o certificado é o deste Client ID"
    SKIPPED+=("teste do token (HTTP $STATUS)")
  fi
  rm -f "$CORPO"
else
  SKIPPED+=("teste do token")
fi
note "Para o motor: GATEWAY=itau, ITAU_CLIENT_ID, ITAU_CLIENT_SECRET, ITAU_CERT_FILE=$CERT, ITAU_KEY_FILE=$CERT_KEY."
note "Com GATEWAY=itau a ida fica DESLIGADA: a emissão espera a Cobrança V2."
pause
# ──────────────────────────────────────────────────────────────────────────

finish
